force-app/main/default/objects/WorkOrderLineItem/fields/TICSample__c.field-meta.xml
<CustomField>
    <fullName>TICSample__c</fullName>
    <label>Sample</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/StatusImageFormula__c.field-meta.xml
<CustomField>
    <fullName>StatusImageFormula__c</fullName>
    <formula>CASE(Status, &apos;New&apos;,&apos;⚪️&apos;, &apos;Pass&apos;,&apos;🟢&apos;, &apos;Fail&apos;,&apos;🔴&apos;,&apos;Fail not reported&apos;,&apos;🟠&apos;,&apos;Under test&apos;,&apos;🔵&apos;,&apos;Remark&apos;,&apos;🟣&apos;,&apos;Not Applicable&apos;,&apos;⚫️&apos;,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Color</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkStep/fields/TICWSGroup__c.field-meta.xml
<CustomField>
    <fullName>TICWSGroup__c</fullName>
    <formula>WorkOrder.WorkOrderNumber + WorkOrderLineItem.TICSample__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WorkStep Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkStepDatatableController.cls
/**
 * @description       : 
 * @author            : maurizio.colombo@lynxspa.com
 * @group             : 
 * @last modified on  : 11-20-2024
 * @last modified by  : maurizio.colombo@lynxspa.com
**/
public without sharing class WorkStepDatatableController {
    @AuraEnabled(cacheable=true)   
    public static List<WorkStep> getWorkStep(boolean flag,String accountName, String opty){
        Map<String, Object> acctBinds = new Map<String, Object>{'accountName' => '%'+accountName+'%', 'opty'=>'%'+opty+'%'}; //, 'SST' => '%'}; //aggiungere valore SST
        String q='select id,workorderId,workorder.OpportunityNumber__c, workorder.WorkOrderNumber,workorder.subject, workorder.account.name, workorder.owner.name, workorderlineitem.subject,workorderlineitem.TICSample__c,name,Description,StatusImageFormula__c,Status,TICWSGroup__c from WorkStep where (workorder.account.name like :accountName and workorder.OpportunityNumber__c like :opty) order by workorder.OpportunityNumber__c ';   //AND workorder.PLSection__c like :SST';
         return Database.queryWithBinds(q,acctBinds,AccessLevel.USER_MODE);
    
    }
 
    @AuraEnabled
    public static String updateWorkStep(Object data){
       List<WorkStep> wsForUpdate = (List<WorkStep>) JSON.deserialize(
          JSON.serialize(data),
          List<WorkStep>.class
     );
     update wsForUpdate;
     return 'Success: workstep updated successfully';
     /*
     try {
         update wsForUpdate;
         return 'Success: contacts updated successfully';
     }
     catch (Exception e) {
         return 'The following exception has occurred: ' + e.getMessage();
     }
         */
    }
 }